### ISSUE TITLE
Android Library Module

### ISSUE THREAD

**Issue by assafco** [CycloneDX/cyclonedx-gradle-plugin#535] opened 2024-11-18 13:32 UTC
**Describe the bug**
If the project inlcudes any Android library module that uses the plugin 'com.android.library' the gradle task fails to produce the sbom file. Java library module on the other hand does not have any problem.

**To Reproduce**
The project should have an Android library module with plugin 'com.android.library', this library should then be used in the app module implementation(project(path: ':AndroidLibrary'))

**Expected behavior**
The gradle task should successfully list all depedencies within the app and create the sbom file.

**Environment  (please complete the following information):**
 - Gradle version [8.5.2]
 - CycloneDX Plugin version [1.10.0]

**Comment by skhokhlov** [comment] 2024-12-12 12:49
It looks like a duplicate of https://github.com/CycloneDX/cyclonedx-gradle-plugin/issues/478 and must be fixed by https://github.com/CycloneDX/cyclonedx-gradle-plugin/pull/539. The changes are not published as a GA release yet, however there is a[ pre-release version 2.0.0-alpha-0 available](https://github.com/CycloneDX/cyclonedx-gradle-plugin/releases/tag/cyclonedx-gradle-plugin-2.0.0-alpha-0). Feel free to test it and send feedback to https://github.com/CycloneDX/cyclonedx-gradle-plugin/issues/478 / reopen this one if you have any concerns.

**Closed by skhokhlov** 2024-12-12 12:49 UTC
Labels: bug

**Comment by assafco** [comment] 2024-12-16 12:12
@skhokhlov I tested version 2.0.0-alpha-0 with my project and it is working correctly without error. Do you know when will the major release will be available?
